### ISSUE TITLE
BiasedUrn

### ISSUE THREAD

**Issue by vnminin** [jasonxu90/branchCorr#3]
Why do we need more colors. Will you vignette work with 32? As it stands now, this note scares users and appears to suggest that in order to use the package, one needs to recompile BiasedUrn.

**Comment by jasonxu90** [comment]
I can make the vignette work with 32, but the colors correspond to barcode
lineages which is a large number for the real data

On Tue, Oct 18, 2016 at 2:56 PM, Vladimir N. Minin <notifications@github.com

**Comment by vnminin** [comment]
Can we copy relevant files/code from BiasedUrn to your package? I think this is allowed under GPL.

**Comment by jasonxu90** [comment]
Wrote my own multivariate hypergeometric sampling function and removed dependency
